/**
 * Note Table with Parameters:
 * - UFixedPoint Q12.7 
 * - Sample Rate: 256
 * - Sample Frequency 22000
 *
 * Generated by gen_note_macros.py
 * Christopher Woodall (c) 2012
 * MIT LICENSE
 * Happy Robot Labs (happyrobotlabs.com), BU EDF (edf.bu.edu)
 *
 * Generates macros for increments for looking into wave tables for
 * note frequencies between C0 and C8
 */
#ifndef _notes_h_
#define _notes_h_

#define C0 0x18
#define Cs0 0x19
#define D0 0x1b
#define Ds0 0x1c
#define E0 0x1e
#define F0 0x20
#define Fs0 0x22
#define G0 0x24
#define Gs0 0x26
#define A0 0x28
#define As0 0x2b
#define B0 0x2d
#define C1 0x30
#define Cs1 0x33
#define D1 0x36
#define Ds1 0x39
#define E1 0x3d
#define F1 0x41
#define Fs1 0x44
#define G1 0x48
#define Gs1 0x4d
#define A1 0x51
#define As1 0x56
#define B1 0x5b
#define C2 0x61
#define Cs2 0x67
#define D2 0x6d
#define Ds2 0x73
#define E2 0x7a
#define F2 0x82
#define Fs2 0x89
#define G2 0x91
#define Gs2 0x9a
#define A2 0xa3
#define As2 0xad
#define B2 0xb7
#define C3 0xc2
#define Cs3 0xce
#define D3 0xda
#define Ds3 0xe7
#define E3 0xf5
#define F3 0x104
#define Fs3 0x113
#define G3 0x123
#define Gs3 0x135
#define A3 0x147
#define As3 0x15b
#define B3 0x16f
#define C4 0x185
#define Cs4 0x19c
#define D4 0x1b5
#define Ds4 0x1cf
#define E4 0x1ea
#define F4 0x208
#define Fs4 0x227
#define G4 0x247
#define Gs4 0x26a
#define A4 0x28f
#define As4 0x2b6
#define B4 0x2df
#define C5 0x30b
#define Cs5 0x339
#define D5 0x36a
#define Ds5 0x39e
#define E5 0x3d5
#define F5 0x410
#define Fs5 0x44e
#define G5 0x48f
#define Gs5 0x4d5
#define A5 0x51e
#define As5 0x56c
#define B5 0x5bf
#define C6 0x616
#define Cs6 0x673
#define D6 0x6d5
#define Ds6 0x73d
#define E6 0x7ab
#define F6 0x820
#define Fs6 0x89c
#define G6 0x91f
#define Gs6 0x9aa
#define A6 0xa3d
#define As6 0xad9
#define B6 0xb7e
#define C7 0xc2d
#define Cs7 0xce6
#define D7 0xdab
#define Ds7 0xe7b
#define E7 0xf57
#define F7 0x1041
#define Fs7 0x1138
#define G7 0x123e
#define Gs7 0x1354
#define A7 0x147a
#define As7 0x15b2
#define B7 0x16fc
#define C8 0x185a
#define Cs8 0x19cd
#define D8 0x1b56
#define Ds8 0x1cf6

#endif

